# Generated by Django 2.0.7 on 2018-07-30 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='FoodListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.FoodItem')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.FoodList')),
            ],
        ),
        migrations.CreateModel(
            name='FoodListItemVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.FoodListItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_leader', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ManyToManyField(to='restaurant.Restaurant')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foodlist',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Party'),
        ),
        migrations.AlterUniqueTogether(
            name='foodlistitemvote',
            unique_together={('item', 'user')},
        ),
    ]
