# Generated by Django 2.0.7 on 2018-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_auto_20180804_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlistitemvote',
            name='vote_type',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
