# Generated by Django 2.1 on 2018-09-04 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('party', '0004_foodlistitemvote_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlistitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='foodlistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='party.FoodList'),
        ),
        migrations.AlterUniqueTogether(
            name='foodlistitem',
            unique_together={('list', 'item')},
        ),
    ]
