version: '3'

services:

  db:
    image: mdillon/postgis:latest
    restart: on-failure
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./src:/code
      - ./volumes/media:/var/www/media
      - ./volumes/static:/var/www/static
      - ./config/nginx/dev:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./volumes/media:/var/www/media
      - ./volumes/static:/var/www/static
      - ./src:/code
    environment:
      - DJANGO_DEBUG=True

    command: bash -c "python ./manage.py collectstatic --noinput && python ./manage.py migrate && gunicorn project_pantry.wsgi -b 0.0.0.0:8000"
