version: '3'

services:

  db:
    image: mdillon/postgis:latest
    restart: on-failure
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./src:/code
      - ./volumes/media:/var/www/media
      - ./volumes/static:/var/www/static
      - ./config/nginx/prod:/etc/nginx/conf.d
      - /etc/letsencrypt/live/wafu.app/fullchain.pem:/etc/letsencrypt/live/wafu.app/fullchain.pem
      - /etc/letsencrypt/live/wafu.app/privkey.pem:/etc/letsencrypt/live/wafu.app/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./volumes/media:/var/www/media
      - ./volumes/static:/var/www/static
      - ./src:/code

    command: bash -c "python ./manage.py collectstatic --noinput && python ./manage.py migrate && gunicorn project_pantry.wsgi -b 0.0.0.0:8000"
