# Generated by Django 2.0.7 on 2018-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180804_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='endorsement',
            field=models.CharField(blank=True, choices=[('TASTE', 'Excellent Taste'), ('HELP', 'Helpful'), ('LEADER', 'Good Leadership')], max_length=25, null=True),
        ),
    ]
